// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/soraQaQ/blog/app/article/internal/biz"
	"github.com/soraQaQ/blog/app/article/internal/conf"
	"github.com/soraQaQ/blog/app/article/internal/data"
	"github.com/soraQaQ/blog/app/article/internal/data/memory"
	"github.com/soraQaQ/blog/app/article/internal/server"
	"github.com/soraQaQ/blog/app/article/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider, registry *conf.Registry) (*kratos.App, func(), error) {
	articleMemory := memory.NewArticleMemoryRepo(logger)
	dataData, cleanup, err := data.NewData(confData, logger, articleMemory)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	articleService := service.NewArticleService(articleUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, articleService, tracerProvider, logger)
	registrar := server.NewRegister(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
